name: Simulation Data Pipeline

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  simulate-and-process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile simulation
        run: make log

      - name: Run simulation until 1GB of data is generated
        run: |
          mkdir -p csv_files
          total_size=0
          run_count=0
          while [ $total_size -lt 268435456 ]; do
            if ! ./a.out > /dev/null; then
              echo "Simulation failed in run $run_count"
            else
              mv *.csv csv_files/
              total_size=$(du -sb csv_files | cut -f1)
            fi

            run_count=$((run_count + 1))
            if [ $((run_count % 200)) -eq 0 ]; then
              echo "Run $run_count: Total data generated so far: $total_size bytes"
            fi
          done
          echo "Finished: Total data generated: $total_size bytes (after $run_count runs)"

      - name: Merge all CSV files into one with timestamped name
        run: |
          cd csv_files
          first_file=$(ls *.csv | head -n 1)
          timestamp=$(date +"%Y-%m-%d_%H-%M-%S")
          merged_file="${timestamp}_control_data.csv"
          cp "$first_file" "$merged_file"
          for file in *.csv; do
            if [ "$file" != "$merged_file" ]; then
              tail -n +2 "$file" >> "$merged_file"
              rm "$file"
            fi
          done

      - name: Compress the merged CSV file
        run: |
          cd csv_files
          gzip -9 *_control_data.csv

      - name: Get compressed filename
        id: get_filename
        run: |
          echo "ASSET_NAME=$(basename csv_files/*_control_data.csv.gz)" >> $GITHUB_ENV
          echo "ASSET_PATH=csv_files/*_control_data.csv.gz" >> $GITHUB_ENV

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: simulation-data-${{ github.run_id }}
          release_name: Simulation Data ${{ github.run_id }}
          draft: false
          prerelease: false

      - name: Upload compressed CSV file to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ASSET_PATH }}
          asset_name: ${{ env.ASSET_NAME }}
          asset_content_type: application/gzip