name: Simulation Data Pipeline

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-simulation:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Run simulation
        id: simulation
        run: |
          make log
          for attempt in {1..10}; do
            echo "Simulation attempt $attempt"
            if ./a.out; then
              echo "Simulation successful"
              break
            fi
            if [ $attempt -eq 10 ]; then
              echo "Maximum attempts reached. Simulation failed."
              exit 1
            fi
          done

      - name: Compress data files
        if: success()
        run: |
          for file in *.csv; do
            [ -f "$file" ] && gzip -9 "$file"
          done

      - name: Create Release and Upload Data
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=$(date +"%Y-%m-%d")
          
          # Create release
          response=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d '{
              "tag_name":"simulation-'"${DATE}"'",
              "name":"Simulation Run '"${DATE}"'",
              "draft":false,
              "prerelease":false
            }')
          
          upload_url=$(echo "$response" | jq -r .upload_url | sed 's/{?name,label}//g')
          
          # Upload compressed files
          for file in *.csv.gz; do
            [ -f "$file" ] && curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -H "Content-Type: application/gzip" \
              "${upload_url}?name=${DATE}_${file}" \
              --data-binary "@$file"
          done