name: Simulation Data Pipeline

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-simulation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile simulation
        run: make log

      - name: Run simulation
        id: simulation
        run: |
          attempt=1
          max_attempts=10
          
          while [ $attempt -le $max_attempts ]; do
            echo "Simulation attempt $attempt"
            if ./a.out; then
              echo "Simulation completed successfully"
              break
            else
              echo "Simulation diverged on attempt $attempt"
              attempt=$((attempt + 1))
              if [ $attempt -gt $max_attempts ]; then
                echo "Maximum attempts reached. Simulation failed consistently."
                exit 1
              fi
            fi
          done

      - name: Create Release
        if: success()
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get current date in YYYY-MM-DD format
          DATE=$(date +"%Y-%m-%d")
          
          response=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d '{
              "tag_name":"simulation-'"${DATE}"'",
              "name":"Simulation Run '"${DATE}"'",
              "draft":false,
              "prerelease":false
            }')
          
          upload_url=$(echo "$response" | jq -r .upload_url | sed 's/{?name,label}//g')
          echo "upload_url=$upload_url" >> "$GITHUB_OUTPUT"

      - name: Upload Simulation Data
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=$(date +"%Y-%m-%d")
          for file in *.csv; do
            if [ -f "$file" ]; then
              curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $GITHUB_TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                -H "Content-Type: text/csv" \
                "${{ steps.create_release.outputs.upload_url }}?name=${DATE}_${file}" \
                --data-binary "@$file"
            fi
          done
