name: Simulation Data Pipeline

on:
  workflow_dispatch:
    inputs:
      simulation_size:
        description: 'Number of simulation iterations'
        required: true
        default: '100000'
        type: string

permissions:
  contents: write

jobs:
  run-simulation:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Run simulation
        run: |
          make log
          for attempt in {1..3}; do
            echo "Simulation attempt $attempt"
            if ./a.out ${{ inputs.simulation_size }}; then
              echo "Simulation successful"
              break
            fi
            if [ $attempt -eq 3 ]; then
              echo "Maximum attempts reached. Simulation failed."
              exit 1
            fi
          done

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Process and upload data
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATETIME=$(date +"%Y-%m-%d_%H-%M-%S")
          CSV_FILE=$(ls *_control_data.csv)
          
          # Compress and split in one operation
          xz -9 < "$CSV_FILE" | split -b 450M - "${CSV_FILE}.xz.part_"
          
          # Create release
          gh release create "simulation-${DATETIME}" \
            --title "Simulation Run ${DATETIME}" \
            --notes "Simulation data from ${DATETIME}"
          
          # Upload parts
          for part in ${CSV_FILE}.xz.part_*; do
            gh release upload "simulation-${DATETIME}" "$part"
          done
          
          rm ${CSV_FILE}.xz.part_*