name: Simulation Data Pipeline

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-simulation:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Run simulation
        run: |
          make log
          for attempt in {1..10}; do
            echo "Simulation attempt $attempt"
            if ./a.out 100000; then
              echo "Simulation successful"
              break
            fi
            if [ $attempt -eq 10 ]; then
              echo "Maximum attempts reached. Simulation failed."
              exit 1
            fi
          done

      - name: Process and upload data
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=$(date +"%Y-%m-%d")
          CSV_FILE=$(ls *_control_data.csv)
          xz -9 "$CSV_FILE"
          
          FILE_SIZE=$(stat -f%z "${CSV_FILE}.xz" 2>/dev/null || stat -c%s "${CSV_FILE}.xz")
          SPLIT_THRESHOLD=$((1800*1024*1024))
          
          response=$(curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d '{"tag_name":"simulation-'"${DATE}"'","name":"Simulation Run '"${DATE}"'","draft":false,"prerelease":false}')
          
          upload_url=$(echo "$response" | jq -r .upload_url | sed 's/{?name,label}//g')
          
          if [ "$FILE_SIZE" -gt "$SPLIT_THRESHOLD" ]; then
            split -b 1G "${CSV_FILE}.xz" "${CSV_FILE}.xz.part_"
            for part in ${CSV_FILE}.xz.part_*; do
              curl -L -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $GITHUB_TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                -H "Content-Type: application/octet-stream" \
                "${upload_url}?name=$(basename ${part})" \
                --data-binary "@${part}"
            done
          else
            curl -L -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -H "Content-Type: application/octet-stream" \
              "${upload_url}?name=$(basename ${CSV_FILE}.xz)" \
              --data-binary "@${CSV_FILE}.xz"
          fi